version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-mschap}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mschap}
      POSTGRES_DB: ${DB_NAME:-mschap_db}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_EXTERNAL_PORT:-5432}:5432"

  server:
    build: ./server
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: ${SERVER_PORT:-8000}
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: ${DB_USER:-mschap}
      DB_PASSWORD: ${DB_PASSWORD:-mschap}
      DB_NAME: ${DB_NAME:-mschap_db}
    depends_on:
      - db

  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "8080:80"

volumes:
  db_data:
